# Generated by Django 4.0.4 on 2022-11-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_favorite', '0003_timemovies'),
    ]

    operations = [
        migrations.AddField(
            model_name='timemovies',
            name='chap',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
