# Generated by Django 4.0.4 on 2022-11-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m'),
        ),
    ]
